<?php 

/**
 * Implements hook_preprocess_page() for page.html.twig.
 */

function clocktower_preprocess_block(array &$variables) {
    $variables['tablist'] = views_embed_view('tab_panel_tabs', 'tabpanel_tabs');
}

function clocktower_preprocess(&$variables, $hook) {
    $variables['base_path'] = base_path();
}


function clocktower_theme_suggestions_block_alter(array &$suggestions, array $variables)
{
  // Block suggestions for custom block bundles.
  if (isset($variables['elements']['content']['#block_content'])) {
    array_splice($suggestions, 1, 0, 'block__bundle__' . $variables['elements']['content']['#block_content']->bundle());
  }
}

/**
 * Implements HOOK_theme_suggestions_HOOK_alter().
 */
function clocktower_theme_suggestions_page_alter(array &$suggestions, array $variables) {

  
  // Add a template suggestions for node type.
  /** @var \Drupal\node\NodeInterface $node */
  if ($node = \Drupal::routeMatch()->getParameter('node')) {
    if (is_numeric($node)) {
      $node = Node::load($node);
    }

    $suggestions[] = 'page__node__' . $node->bundle();
  }
}


function clocktower_form_views_exposed_form_alter(&$form, &$form_state, &$form_id) {
  if ($form_id == 'views_exposed_form' && $form['form_id']['#id'] == 'edit-views-exposed-form--2') {
    $form['actions']['submit']['#value'] = html_entity_decode('&#xf0a9;');
    $form['actions']['submit']['#attributes']['aria-label'] = "Search";
  }

  if ($form_id = 'views-exposed-form-search-search-page') {
      $form['actions']['submit']['#value'] = html_entity_decode('&#xf002;');
      $form['actions']['submit']['#attributes']['aria-label'] = "Search";
  }

}

/**
 * Implements HOOK_theme_suggestions_HOOK_alter().
 */
function clocktower_theme_suggestions_html_alter(array &$suggestions, array $variables) {
  // Add a template suggestions for node type.
  /** @var \Drupal\node\NodeInterface $node */
  if ($node = \Drupal::routeMatch()->getParameter('node')) {
    if (is_numeric($node)) {
      $node = Node::load($node);
    }

    $suggestions[] = 'html__node__' . $node->bundle();
  }
}


function clocktower_preprocess_views_view_field(&$variables) {

 $variables['output'] = $variables['field']->advancedRender($variables['row']);

}

function clocktower_preprocess_menu(&$variables) {
  try {
    $variables['is_front'] = \Drupal::service('path.matcher')->isFrontPage();
  }
  catch (Exception $e) {
    $variables['is_front'] = FALSE;
  }
}


function clocktower_theme() {
  return [
    'layout_twocol_with_header' => [
      'template' => 'templates/twocol-with-header',
      // layout_plugin expects the theme hook to be declared with this:
      'render element' => 'content',
      'base hook' => 'layout',
    ],
    'layout_threecol_with_header' => [
      'template' => 'templates/threecol-with-header',
      // layout_plugin expects the theme hook to be declared with this:
      'render element' => 'content',
      'base hook' => 'layout',
    ],
  ];
}
